usrname:
password:

sql:
  sqlone: select * from tablename
  sqlall: select * from tablename

mysql:
  username: root
  password: 123456
  ip: 127.0.0.1
  port: 3306
  databases:
    - mysite7


ob:
  username: dbhub
  password: dbhub
  ip: 127.0.0.1
  port: 8080
  databases:
    - dbhub
    - dbrisk

path:
  # 启动游戏
  game_path: E:\moshou\battlenet\Battle.net\Battle.net.exe
  win_path: D:\TOOLS\DeadFishKnight\config\pictures\win_logs\cmd_result.png
  start_game: D:\TOOLS\DeadFishKnight\config\pictures\login\start_game.png

  # 游戏模式
  adventure_model: D:\TOOLS\DeadFishKnight\config\pictures\model\冒险模式.png
  practice_model: D:\TOOLS\DeadFishKnight\config\pictures\model\练习模式.png

  # 难度选择
  normal_model: D:\TOOLS\DeadFishKnight\config\pictures\model\普通难度.png


settings:
  # 游戏配置
  PAUSE: 2


position:
  common:
    x: 974  # 开始按钮
    y: 848